### ISSUE TITLE
Improve plugin package test coverage

### ISSUE THREAD

**Issue by GeertJohan** [go-flutter-desktop/go-flutter#109]
The plugin package is still missing some tests, coverage can be increased.

Required for: https://github.com/avelino/awesome-go/pull/2431

**Comment by drdgvhbh** [comment]
Just want to chim in on how to test these plugins.

You basically just need to do a [manual install] in your plugin directory and then set `export LD_LIBRARY_PATH=$PWD`, otherwise you'll get an error like this when running the tests: `/tmp/go-build321691715/b001/file_picker.test: error while loading shared libraries: libflutter_engine.so: cannot open shared object file: No such file or directory
`.

**Comment by Drakirus** [comment]
>  A lot of the go-flutter code is about wiring together GLFW and Flutter, which cannot effectively be mocked. We could add "fake tests" to just add coverage, but that's not useful at all. 

Not top priority, to me what's needs coverage is codec, and codec are pretty well tested.
Don't want to fight for a stupid awesome list.
