### ISSUE TITLE
could not import github.com/go-flutter-desktop/go-flutter

### ISSUE THREAD

**Issue by jascodes** [go-flutter-desktop/go-flutter#210]
Do in need to go get go-flutter to fix the following issue?

![Screenshot from 2019-07-25 09-04-50](https://user-images.githubusercontent.com/1231593/61844011-9bf2aa80-aebb-11e9-8b17-af230211108e.png)
![Screenshot from 2019-07-25 09-04-55](https://user-images.githubusercontent.com/1231593/61844012-9bf2aa80-aebb-11e9-8aac-ba462b604384.png)
![Screenshot from 2019-07-25 09-04-59](https://user-images.githubusercontent.com/1231593/61844015-9bf2aa80-aebb-11e9-8cbe-841d2f5e4cd4.png)

But when I try to ` go get -u github.com/go-flutter-desktop/go-flutter`
I get following error
```
# github.com/go-flutter-desktop/go-flutter/embedder
/usr/bin/ld: cannot find -lflutter_engine
collect2: error: ld returned 1 exit status
```

I have not issues with comipling with`hover run` or `hover build`

Thx

**Comment by jascodes** [comment]
I am still getting error but all of sudden issue seem to be fixed

![Screenshot from 2019-07-25 09-50-46](https://user-images.githubusercontent.com/1231593/61845629-baf43b00-aec1-11e9-813d-8cef71a84a48.png)

Now I have quesion how and where we are importing option variable from option.go file, because setup works. Is somthing wrong with linter?

![Screenshot from 2019-07-25 09-50-59](https://user-images.githubusercontent.com/1231593/61845632-bc256800-aec1-11e9-867d-4958be1bf1c1.png)

**Comment by Drakirus** [comment]
I can see that you are using `LSP`, the [`gopls`](https://godoc.org/golang.org/x/tools/cmd/gopls) is famous for been a bit freakish.

The issue from: `go get -u github.com/go-flutter-desktop/go-flutter` occurs because your `CGO_LDFLAGS` isn't correct. When using the tool `hover`, we are setting the `CGO_LDFLAGS` to the correct path (on linux: `export CGO_LDFLAGS="-L/home/drakirus/.cache/hover/engine/linux/"`)

For linting I use, [`ALE`](https://github.com/w0rp/ale), it works out of the box. Having linting error in `main.go` isn't a issue as the file souldn't be modified. You don't seems to have LSP errors in `option.go` that what matters the most.

**Comment by Drakirus** [comment]
If you don't have any other question, or if my answer is enough, please close the issue. :wink:

**Comment by AppliNH** [comment]
Hello ! I also work in VSCode, and I have this "LSP error" in all the go files where "github.com/go-flutter-desktop/go-flutter" is imported.
Setting `CGO_LDFLAGS` env variable doesn't change anything to that.

Any idea ?
