### ISSUE TITLE
[Need help] About Hot reload in android studio.

### ISSUE THREAD

**Issue by CaiJingLong** [go-flutter-desktop/go-flutter#213]
I have seen that hover can be connected to vscode in a certain way ,as #129 , and even theoretically can complete this process through plugins?
So Android Studio/Intellij Idea can do this?

**Comment by Drakirus** [comment]
> even theoretically can complete this process through plugins?

I'm not understanding the question.  

> So Android Studio/Intellij Idea can do this?

If you are speaking about hot-reload using Intellij, the current flutter extension dosn't support it.

An issue has been opened on the flutter-intellij issue tracker, please follow: https://github.com/flutter/flutter-intellij/issues/2250. If the feature gets implemented, please report back on this issue and we will provide the instruction to 'connect' hover to Intellij.

Closing the issue for now. I will say subscribed to the feed.

**Comment by StefanLobbenmeier** [comment]
I know this issue is closed, but I found a slightly better way to launch hover in Android Studio / IntelliJ and wanted to share. [This is my source](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206883315-Anyway-to-Make-IntelliJ-IDEA-run-command-line-commands)

I added hover as an External Tool like this:
![image](https://user-images.githubusercontent.com/36509607/64944287-58d70700-d86e-11e9-9315-1771cdae264c.png)

And now I can launch my flutter app in hover by going into Tools - External Tools - Hover

I prefer this over having it run in a terminal Tab, since it groups nicely with other applications I ran in the Run tab:

**Comment by ContainsK** [comment]
> I know this issue is closed, but I found a slightly better way to launch hover in Android Studio / IntelliJ and wanted to share. [This is my source](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206883315-Anyway-to-Make-IntelliJ-IDEA-run-command-line-commands)
> 
> I added hover as an External Tool like this:
> ![tmp](https://user-images.githubusercontent.com/36509607/64946192-950c6680-d872-11e9-8ba4-b00569e9d271.png)
> 
> And now I can launch my flutter app in hover by going into Tools - External Tools - Hover
> 
> I prefer this over having it run in a terminal Tab, since it groups nicely with other applications I ran in the Run tab:
> ![tmp](https://user-images.githubusercontent.com/36509607/64944763-5f19b300-d86f-11e9-9f2f-3947d476d941.png)

Have you finished debugging windows in IntelliJ ？

**Comment by StefanLobbenmeier** [comment]
What do you mean „finished“?

If you mean if I could attach a debugger - then sadly no. I never tried to either. I guess this should  raise a separate issue, my guess is that you can actually attach a debugger to the dart VM after the app started like you can with Java
