### ISSUE TITLE
Copy build files to build/desktop instead of desktop/build/outputs

### ISSUE THREAD

**Issue by jld3103** [go-flutter-desktop/go-flutter#242]
All other platforms copy their build files to ```build/platform```. Hover copies them to ```desktop/build/outputs```.
They should be under ```build/desktop```.

**Comment by Drakirus** [comment]
We are considering changing directory named created by hover from `desktop` to `go`, #209.
We aren't part of the flutter team, so I don't like to interfere too much with the current directory layout.

That been said, the build directory is ignored in the `.gitignore` file, copying hover build files to `build/go` shouldn't cause any issue. It is also better for cleaning because `flutter clean` will delete the files created by `hover`

**Comment by GeertJohan** [comment]
See go-flutter-desktop/hover#14

**Comment by GeertJohan** [comment]
That sounds great @stuartmorgan!

I agree with @Drakirus about not interfering with the directory layout. Other directories in a flutter project are "owned" by other tools. Inside the `go` directory (now still `desktop`) we can do what we want without much chance of conflicts.

**Comment by GeertJohan** [comment]
Closing this issue, we'll stick with the `go` folder for now.
