### ISSUE TITLE
hover: Failed to fetch full sha for engine version 4b22bc1bd9 from GitHub

### ISSUE THREAD

**Issue by joeblew99** [go-flutter-desktop/go-flutter#244]
Just started to fail.
failing on examples and other projects.

I am using flutter master because i also use flutter web.

## Flutter version

```
apple$ flutter --version
Flutter 1.9.8-pre.38 • channel master • https://github.com/flutter/flutter.git
Framework • revision c4d54743b1 (15 hours ago) • 2019-08-31 16:35:41 -0400
Engine • revision 4b22bc1bd9
Tools • Dart 2.5.0 (build 2.5.0-dev.4.0 36985859e4)
```

## Golang errors (Optional)

```

cd /Users/apple/workspace/go/src/github.com/go-flutter-desktop/examples/stocks && hover run
hover: Failed to fetch full sha for engine version 4b22bc1bd9 from GitHub
make: *** [flu-desk-run] Error 1


```

**Comment by Drakirus** [comment]
After a bit of waiting, does `hover run` works?

**Comment by Drakirus** [comment]
I think the issue comes for too much request to the GITHUB API.
For users that hit the GITHUB API rate limit, please do the following:  
 - create a github token https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line
 - `GITHUB_TOKEN=afab9ab158cXXXXXXXXXXXXXXXXXXXXXXXXXXXXX hover run`

The `GITHUB_TOKEN` can be added as a env variable in .bashrc

**Comment by joeblew99** [comment]
Sorry it was me. I had an old hover binary.. :) thanks

**Comment by joeblew99** [comment]
@Drakirus You were right. It was my hitting github too much.
happened to me again today.
