### ISSUE TITLE
Set the initial window dimension based on screen resolution

### ISSUE THREAD

**Issue by jascodes** [go-flutter-desktop/go-flutter#267]
I wanted to set the initial dimension of the window based on the scale of the desktop environment the app is running. I was trying to find if it is possible at this moment to do so.

Thx

**Comment by jascodes** [comment]
In adition to desktop scale, is it possible to get screen resolution. It makes sense to know screen resolution and then set initial screen size based on that.

**Comment by Drakirus** [comment]
Before answering any question make sure to be aware of #84 .
So desktop scale is currently an issue, not possible for now.

Regarding getting the screen resolution & set initial screen size, I will hack a [Tips-and-tricks](https://github.com/go-flutter-desktop/go-flutter/wiki/Tips-and-tricks) go file to throw into your `go/cmd/` directory later. 
Spoiler alert, need a [`GLFW Plugin`]{https://github.com/go-flutter-desktop/go-flutter/wiki/GLFW-Plugin-example) and will be a bit wacky, since initial size is defined set before the plugin is created.

**Comment by Drakirus** [comment]
[Tips-and-tricks#2](https://github.com/go-flutter-desktop/go-flutter/wiki/Tips-and-tricks#2-set-the-initial-window-dimension-based-on-screen-resolution)
