### ISSUE TITLE
Unrecognized developer macOS & windows

### ISSUE THREAD

**Issue by huextrat** [go-flutter-desktop/go-flutter#281]
Hi,
It is impossible to install a build (.pkg) build on macOS 10.14 & 10.15 at least, an error is shown during the installation 
```
The installation failed
The installation program cannot locate the data necessary to install the software
```
and on windows we must force the installation by accepting the installation of an app from an unrecognized developer.

Do you know a way not to have this problem?

## Flutter version

```
Flutter 1.10.7-pre.99 • channel master • https://github.com/flutter/flutter
Framework • revision 2de1e4f4a1 (2 weeks ago) • 2019-09-30 22:05:53 -0400
Engine • revision 4981512815
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 692230b484)
```

## Steps to Reproduce

1. hover build darwin-pkg | hover build windows-msi
2. try to install the application on your computer
3. macOS refuses the installation of a pkg
4. windows a popup is shown to force the installation because developer is not recognized

**Comment by Drakirus** [comment]
Does it work on the flutter beta channel?

**Comment by Drakirus** [comment]
Ping @jld3103

**Comment by huextrat** [comment]
> Does it work on the flutter beta channel?

I just tried it on beta & stable and I got exactly the same 'issue', also I'm building the app on macOS 10.15 if it can help 👍

**Comment by jld3103** [comment]
@huextrat 
The MacOS issue is already fixed (https://github.com/go-flutter-desktop/hover/commit/0566c890d116492b329f01d79655855113ba2537). You need to update hover and then re-init darwin-pkg (delete the folder and then do `hover init-packaging darwin-pkg` again).

The unknown developer issue has nothing to do with go-flutter. When you just create a .msi you are always an unknown developer. You have to register yourself somehow at Microsoft, but I have no plan about that.

**Comment by Drakirus** [comment]
As @jld3103 said, this issue was fixed in the latest version of hover, please upgrade.  
(`go get -u github.com/go-flutter-desktop/hover`).

After the updates finishes, delete the `go/packaging/` directory and rerun the `hover init-packaging darwin-pkg` command.

Finally run `hover build darwin-pkg` to produce a valid darwin  pkg.

Concerning 
> On windows, a popup is shown to force the installation because developer is not recognized.

It's up to you to tweak the developer ID (I don't actually know how this work) in the msi template file located under `go/packaging/windows-msi/$PROJECT_NAME.wxs`
