### ISSUE TITLE
SelectableText is not working in go-flutter

### ISSUE THREAD

**Issue by Tokenyet** [go-flutter-desktop/go-flutter#285]
[√] Flutter (Channel unknown, v1.10.12, on Microsoft Windows [Version 10.0.18362.388], locale zh-TW)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code, 64-bit edition (version 1.38.1)
[!] Connected device
    ! No devices available

## Steps to Reproduce
Just add a `SelectableText` with some text, and It's not copyable with `ctrl+c`. Maybe It's designed to use popup copy in mobile, but there is no function supported in desktop?

**Comment by Drakirus** [comment]
I just spend a loot of time looking at `SelectableText` (https://github.com/chunhtai/flutter/blob/master/packages/flutter/lib/src/material/selectable_text.dart) and from my unbdersanding the flutter/flutter framework doesn't exposes the text selection value with the embedder (the one that handle ctrl-c)

**Comment by Drakirus** [comment]
The `SelectableText` isn't sending message to the embedder because of [this](https://github.com/flutter/flutter/blob/e7ffac2d67203ff3e57a01f762fb5374955d14cd/packages/flutter/lib/src/widgets/editable_text.dart#L1385-L1387).
The line needed to notify the embedder (go-flutter) editing state: [`setEditingState`](https://github.com/flutter/flutter/blob/e7ffac2d67203ff3e57a01f762fb5374955d14cd/packages/flutter/lib/src/widgets/editable_text.dart#L1415)  (calls to a platform method channel [here](https://github.com/flutter/flutter/blob/1c535de7e0714253c3d71ef8af07b1ea27e2e586/packages/flutter/lib/src/services/text_input.dart#L665-L672))

**Comment by Drakirus** [comment]
Can you please open a issue on flutter/flutter?
(and reference this issue in the flutter/flutter tracker if needed)

**Comment by Tokenyet** [comment]
Thanks for taking care this issue! I opened this issue 😄

**Comment by pchampio** [comment]
This issue is fixed in Flutter 1.12 stable.

```
❯ flutter --version
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter
Framework • revision 27321ebbad (2 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
```
The flutter/flutter framework is using the ["flutter/keyevent"](https://github.com/go-flutter-desktop/go-flutter/blob/master/key-events.go#L62) BasicMessageChannel to register the copy event on the framework side.
The framework is then sending the text content through the ["Clipboard.setData" method of "flutter/platform"](https://github.com/go-flutter-desktop/go-flutter/blob/f223ac0af05e98652479444f720d4f4b1bb57b2f/platform.go#L49) in the same manner as it is done when the user clicks the copy popup button.

**Comment by pchampio** [comment]
As we are using [RawKeyEventDataLinux (GLFW compatible)](https://github.com/flutter/flutter/blob/6e72facad1d4bc28384cb8b38d57de8f1de2aa15/packages/flutter/lib/src/services/raw_keyboard_linux.dart#L166) this means the flutter framework would need have different handles for modifier keys on different platforms. i.e. different handles on (linux/macos/window) (ctrl-c vs cmd-c) for the SAME render-er backend (GLFW in your case).

**Comment by pchampio** [comment]
The issue of using the flutter/keyevent to interact with keyboard shortcut/text movement is described in https://github.com/go-flutter-desktop/go-flutter/issues/314.
Closing this issue.
