### ISSUE TITLE
Hover build fails with whitespace in path

### ISSUE THREAD

**Issue by xaxys** [go-flutter-desktop/go-flutter#378]
## Error output

Using `hover build windows` to build my application, I get the following
error:

```log
hover: Using engine from cache
hover: Cleaning the build directory
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Bundling flutter app
'C:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
hover: Flutter build failed: exit status 1
```

Obviously, It is caused by whitespace in flutter path (I installed flutter in C:\Program Files\flutter).I checked the source of hover, found the error @ (build.go:436).
It seems hover uses the full path of Flutter/Go/Docker etc. So I tried to warp the path with `"`, but it will cause an error when warpping command of `Cmd`, go will check the command first(exec.go:382), which doesn't allow a command with `"`.(args are fine with `"`). so I come for help. 
It seems easiler to use `flutter` `go` command directly instead of its full path, and that's my solution temporarily.

**Comment by pchampio** [comment]
Can you create a PR that fixes this issue?

**Comment by GeertJohan** [comment]
Thanks for opening this PR @xaxys.

The fix you propose may work well on your machine, but could introduce errors for other users. A proper fix should make the executable path working even with spaces, probably the spaces must be escaped.

Please wait for https://github.com/go-flutter-desktop/hover/pull/73 to be merged, because it may fix your issue as a side effect. I changed some of the inner workings in that version.

**Comment by xaxys** [comment]
Sure, I'll be waiting, Thx.

**Comment by pchampio** [comment]
@xaxys with the latest version of hover, do you still encounter this bug?

**Comment by xaxys** [comment]
It works well now, thank you for your work.
