### ISSUE TITLE
Docker: no matching manifest for windows/amd64 10.0.17763 in the manifest list entrie

### ISSUE THREAD

**Issue by Winwisly100** [go-flutter-desktop/go-flutter#386]
Hello
I got this error when building windows-msi in Github's actions.
https://github.com/Winwisly100/simple/runs/563940693?check_suite_focus=true

**Comment by jld3103** [comment]
My first search lead to the answer that it is an windows docker issue. But anyway why are you using windows to build it? Packaging for msi is done in a docker container and works perfectly on linux. I would suggest to use ubuntu as the host and then it should work.

I'm closing this issue, because it's not a hover bug.

**Comment by Winwisly100** [comment]
@jld3103 ok thanks
