### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by jinfagang** [go-flutter-desktop/go-flutter#391]
```
go get github.com/go-flutter-desktop/go-flutter
# github.com/go-flutter-desktop/go-flutter/embedder
/usr/bin/ld: cannot find -lflutter_engine
collect2: error: ld returned 1 exit status
# github.com/go-gl/glfw/v3.3/glfw
/usr/bin/ld: cannot find -lXxf86vm
collect2: error: ld returned 1 exit status

```

**Comment by pchampio** [comment]
This is a known issue, go-flutter needs to be compiled with specific flag in order to find the engine shared library.

Does everything works properly when using hover??

Why did you go get go-flutter and didn't used hover?

**Comment by pchampio** [comment]
This is a known issue, go-flutter needs to be compiled with specific flag in order to find the engine shared library.

Closing this issue:
* [go-flutter wiki on manual compilation](https://github.com/go-flutter-desktop/go-flutter/wiki/Setting-up-hover-to-use-a-home-made-version-of-'go-flutter')
* Issue about `-lXxf86vm` https://github.com/go-gl/glfw/issues/140

**Comment by ykmnkmi** [comment]
fedora 32 same error.
fixed by installing libXxf86vm-devel.
