### ISSUE TITLE
Is toast related plugin can be supported in go-flutter?

### ISSUE THREAD

**Issue by jinfagang** [go-flutter-desktop/go-flutter#424]
```
go-flutter: no handler found for channel PonnamKarthik/fluttertoast

```

Some common used toast package can not found. Any options for this ? I think many mobile platform will use toast more or less, is there a standard way to replace toast on both mobile side or desktop side?

**Comment by pchampio** [comment]
That is because go-flutter doesn't have an implementation for that plugin. You may ask the plugin maintainer to add an implementation or you create one yourself.

The go-flutter team has implemented flutter maintained plugins: https://github.com/go-flutter-desktop/plugins
We don't plan to work on community based plugins.
Closing this issue.
