### ISSUE TITLE
go-flutter: no handler found for channel flutter/isolate

### ISSUE THREAD

**Issue by jinfagang** [go-flutter-desktop/go-flutter#425]
```
go-flutter: no handler found for channel flutter/isolate

```

**Comment by pchampio** [comment]
That is because go-flutter doesn't have an implementation for that plugin. You may ask the plugin maintainer to add an implementation or you create one yourself.

The go-flutter team has implemented flutter maintained plugins: https://github.com/go-flutter-desktop/plugins
We don't plan to work on community based plugins.
Closing this issue.
