### ISSUE TITLE
hover: use same binary in docker as on host machine.

### ISSUE THREAD

**Issue by james-lawrence** [go-flutter-desktop/go-flutter#430]
docker container uses an internal version of hover vs using the host version. (makes modifying hover to debug difficult.

**Comment by jld3103** [comment]
It's actually easy to update the binary, because you can simply overwrite the docker image. There is a script for that in the hover repo that installs hover locally and updates the docker image.
But still we could try to improve the development time, because the container has to download and compile the dependencies on every image build.

**Comment by GeertJohan** [comment]
Hover will try to use a docker container image for hover with the same version as the host hover. So the hover binary inside the docker container will be the same as the version of the host hover binary.

Relevant code is in [docker.go:91](https://github.com/go-flutter-desktop/hover/blob/master/cmd/docker.go#L91)

If you're developing locally, run this command to build and install hover.

```bash
go install . && DOCKER_BUILDKIT=1 docker build . -t goflutter/hover:latest
```

A locally built hover will always use `goflutter/hover:latest`, which you've just built using local sources as well. So the binaries will be in sync.

`DOCKER_BUILDKIT=1` is optional. I like it better than the normal `docker build`.
