### ISSUE TITLE
Please support menubar

### ISSUE THREAD

**Issue by jlcool** [go-flutter-desktop/go-flutter#431]
https://github.com/google/flutter-desktop-embedding/tree/master/plugins/menubar

**Comment by pchampio** [comment]
This is another plugin request.

The go-flutter doesn't have an implementation for that plugin. You may create one yourself and open a PR on https://github.com/go-flutter-desktop/plugins

The go-flutter team doesn't have the resource to implement all plugins, PLEASE help us.
### Wiki:
- https://github.com/go-flutter-desktop/go-flutter/wiki/Plugin-info
- https://github.com/go-flutter-desktop/go-flutter/wiki/Create-a-hover-compatible-plugin
- https://github.com/go-flutter-desktop/go-flutter/wiki/Implement-a-plugin
- https://github.com/go-flutter-desktop/go-flutter/wiki/GLFW-Plugin-example
### Examples:
- https://github.com/go-flutter-desktop/plugins
### Tutorial example:
- https://github.com/go-flutter-desktop/examples/tree/master/plugin_tutorial

Closing this issue because the go-flutter team will not work on this plugin.
Still,
You can report your advancement/questions in this issue.
We also have a gitter chat: https://gitter.im/go-flutter-desktop/go-flutter .
