### ISSUE TITLE
What's the status on AOT?

### ISSUE THREAD

**Issue by ganeshrvel** [go-flutter-desktop/go-flutter#496]
What's the status on AOT for macos? Are there any issues implementing it for flutter macos?

How different is the performance of a AOT compiled app with regards to JIT?

**Comment by jld3103** [comment]
[This](https://github.com/go-flutter-desktop/go-flutter/issues/259) is the general issue and [this](https://github.com/go-flutter-desktop/hover/pull/147) is the PR that worked for about two weeks, but the flutter team made changes so it's no longer possible to use it. Also the PR only worked on Linux and Windows, because of some error that I still don't understand. To get it working again we need https://github.com/flutter/flutter/issues/44577 from the flutter team. There already has been some discussion so I hope we get something we can use in the future.
