### ISSUE TITLE
Request: Add support for the flutter_secure_storage plugin

### ISSUE THREAD

**Issue by gargakshit** [go-flutter-desktop/go-flutter#508]
Request for support of the plugin `flutter_secure_storage`.

That plugin is a crucial part of my application, as support for that would be a no-brainer for me to use go-flutter

Thanks

**Comment by jld3103** [comment]
I think it's not possible directly, because the official plugins use a secure storage provided by the OS which is uncommon for desktop OS's. You could use some keychain apps/system to build your own implementation for the plugin, but that seems to be a bit over the top.
Depending on your usecase you could also change what and how you store it so that it is secure, but that also may not be possible.

**Comment by gargakshit** [comment]
Thank you for a timely reply! Looks like you are right. As far as I know only Macos provides an official implementation. My usecase was to store encryption keys, which I can surely not store using shared prefs or something similar. Could you please suggest an alternative.

Thanks

**Comment by jld3103** [comment]
I think there is no way. Sensitive data on desktop is just stored as it is. Think of your ssh key in `~/.ssh`

**Comment by gargakshit** [comment]
So I am closing the issue. Final thing I did: I used plain sharedprefs as all the data stored there was hashed anyways
