### ISSUE TITLE
Does the repo gived up maintained? Windows how packaging a single exe file?

### ISSUE THREAD

**Issue by jinfagang** [go-flutter-desktop/go-flutter#519]
This is a very good  solution for flutter generate desktop applications, why does this repo commit so rare? All newest issue is fire by me, is there only have a faith this project?

Windows how to packaging a single exe file? Any maintainer can help me figure out a solution with this?

**Comment by jinfagang** [comment]
I mean, without flutter-engine.so related files. We can have AppImage packaging all togather but how about windows?

**Comment by jld3103** [comment]
This project didn't have much development in the last time, because we all have not that much time for it.
I see all your issues, but sometimes I don't know how to help or don't have time to help. Sorry for that.

It isn't possible to pack the app into a single exe file. You can only use the msi.

**Comment by jinfagang** [comment]
@jld3103 Thank you! Now I don't know should using this for flutter desktop or using flutter official one. The downside of flutter official is that it doesn't have any plugin support at all (not even sqlite). Can u shine a light on me?

Then how do I using msi, using hover build doesn't generate such a file.

**Comment by jld3103** [comment]
For the future and in the long run I guess the official flutter desktop will be better, because it's official and they will maintain it.
From the plugin side they have much less support so go-flutter is currently better regarding that.
The great thing is that you can use both at the same time so you can use whatever works best in your scenario.
The advantage of go-flutter/hover is that you have the packaging.
To build the msi run `hover init-packaging windows-msi` once and then use `hover build windows-msi` to build it.

**Comment by jld3103** [comment]
Can this be closed?
