### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by prologic** [go-flutter-desktop/go-flutter#670]
This is not really a feature request per se, if you open up the "Discussions" feature, feel free to convert this to a discussion.

Q: Is Mobile support possible and well supported [as per this blog post](https://morioh.com/p/d20df0199c40) and [old codebase showing how to do this](https://github.com/kjcodeacct/golang_flutter_demo)?

Thanks!

**Comment by pchampio** [comment]
I didn't know this blog post. It does a nice introduction of go-flutter!

go-flutter is another [desktop embedder](https://github.com/go-flutter-desktop/go-flutter#purpose).
![image](https://user-images.githubusercontent.com/7476655/180647703-ba6e0bf4-d8e7-46a2-8018-c4ffab6a213c.png)

no work has been done into making into making it compatible for mobile.
I'll argue that the official iOS and Android embedders are simply the best and do not need alternative, the is no plan to make go-flutter compatible for mobile.

---

This project exist because, one of the advantages of go-flutter is golang:
> The choice of [Golang](https://github.com/golang/go) comes from the fact that it has the same tooling on every platform. Plus Golang is a great language because it keeps everything simple and readable, which makes it easy to build cross-platform plugins.

While not documented one could build a generic golang library and compile it to be used by official iOS and Android embedders [here is an example](https://divan.dev/talks/2019/gdgbcn/FlutterGomobile.pdf), additional this golang library can also directly be used as a go-flutter plugin.

An example of a such plugin is: https://github.com/jerson/flutter-rsa

---
To answer your question: 
> Is Mobile support possible

Not at the embedder / tooling  / ios/android packaging level, don't expect so see a `hover build ios` / `hover build android` any time.
On the other hand Golang plugin are by support by all embedders, but it's kinda of niche application.
